<?php ob_start() ?>

<h1>mdref</h1>

<?php if (isset($html)) : ?>
	<?= $html ?>
<?php elseif (isset($text)) : ?>

	<p style="white-space:pre-wrap"><?= $esc($text) ?></p>
<?php elseif (isset($refs)) : ?>
	<?php foreach ($refs as $repo) : /* @var \mdref\Repo $repo */ ?>
		<?php foreach ($repo as $root) : /* @var \mdref\Entry $root */ ?>

		<h2 id="<?= $anchor($root->getTitle()) ?>">
			<a href="<?= $esc($root->getName()) ?>"
			><?= $esc($root->getTitle()) ?></a></h2>
		<div><?= $quick($root->getIntro()) ?></div>
			<?php if ($repo->hasStub($stub)) : ?>
				<?php include __DIR__ . "/stub.phtml"; ?>
			<?php endif; ?>
		<?php endforeach; ?>
	<?php endforeach; ?>
<?php endif; ?>

<?= $markup(ob_get_clean()); ?>
