<h1>mdref</h1>

<?php if (isset($html)) : ?>
	<?= $html ?>
<?php elseif (isset($text)) : ?>
	<p style="white-space:pre-wrap"><?= $view->esc($text) ?></p>
<?php elseif (isset($refs)) : ?>
	<?php foreach ($refs as $repo) : /* @var \mdref\Repo $repo */ ?>
		<?php foreach ($repo as $entry) : /* @var \mdref\Entry $entry */ ?>
		<h2>
			<a href="<?= $view->esc($entry->getName()) ?>"
			><?= $view->esc($entry->getTitle()) ?></a></h2>
		<div><?= $quick($entry->getIntro()) ?></div>
		<?php endforeach; ?>
	<?php endforeach; ?>
<?php endif; ?>