<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<title>
			<?php if (!empty($title)) : ?>
				<?= $title ?> -
			<?php endif; ?>
				mdref
		</title>
		<base href="<?= $baseUrl ?>">
		<link rel="stylesheet" href="index.css">
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
	</head>
	<body>
		<?php include __DIR__."/sidebar.phtml" ?>
		
		<?php if (isset($html)) : ?>
			<?php include __DIR__."/mdref.phtml" ?>
		<?php else: ?>
			<?php include __DIR__."/index.phtml" ?>
		<?php endif; ?>

		<div id="disqus_thread"></div>

		<footer>
			<?php include __DIR__."/footer.phtml" ?>
		</footer>
		<script src="index.js"></script>
	</body>
</html>
