<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<title>
			<?php if (!empty($title)) : ?>
				<?= $title ?> -
			<?php elseif (isset($entry)) : ?>
				<?= $entry ?> -
			<?php endif; ?>
			mdref
		</title>
		<meta name="viewport" content="width=1200, initial-scale=0.5">
		<?php if (isset($baseUrl)) : ?>
			<base href="<?= $baseUrl ?>">
			<meta http-equiv="Content-Location" content="<?= $baseUrl . $ref ?>">
			<link rel="stylesheet" href="index.css">
		<?php endif; ?>

		<link href="https://fonts.googleapis.com/css?family=Inconsolata&amp;subset=latin-ext" rel="stylesheet">
		<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
		<link rel="shortcut icon" href="<?= $baseUrl . "favicon.ico" ?>">
	</head>
	<body>
		<div class="page">
		<?php include __DIR__."/sidebar.phtml" ?>
		<?php if (isset($exception)) : ?>
			<?= \mdref\ExceptionHandler::htmlException($exception) ?>
		<?php elseif (isset($entry)) : ?>
			<?php include __DIR__."/mdref.phtml" ?>
		<?php else: ?>
			<?php include __DIR__."/index.phtml" ?>
		<?php endif; ?>

		<?php if (@$_SERVER["SERVER_NAME"] != "localhost") : ?>

			<div id="disqus_thread"></div>
			<script>
				var disqus_shortname = 'mdref';
				var disqus_identifier = '<?=$ref?>';
				(function() {
					var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
					dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
					(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
				})();
			</script>
		<?php endif; ?>

			<footer>
				<?php include __DIR__."/footer.phtml" ?>

			</footer>
		<?php if (isset($baseUrl)) : ?>

			<script src="index.js"></script>
		<?php endif; ?>

		</div>
	</body>
</html>
