<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<title>
			<?php if (!empty($title)) : ?>
				<?= $title ?> -
			<?php elseif (isset($entry)) : ?>
				<?= $entry ?> -
			<?php endif; ?>
			mdref
		</title>
		<?php if (isset($baseUrl)) : ?>
			<base href="<?= $baseUrl ?>">
			<meta http-equiv="Content-Location" content="<?= $baseUrl . $ref ?>">
			<link rel="stylesheet" href="index.css">
		<?php else: ?>
			<style type="text/css">
				<?= file_get_contents(__DIR__."/../public/index.css"); ?>
			</style>
		<?php endif; ?>
		
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
	</head>
	<body>
		<?php include __DIR__."/sidebar.phtml" ?>
		<?php if (isset($exception)) : ?>
			<?= \mdref\ExceptionHandler::htmlException($exception) ?>
		<?php elseif (isset($entry)) : ?>
			<?php include __DIR__."/mdref.phtml" ?>
		<?php else: ?>
			<?php include __DIR__."/index.phtml" ?>
		<?php endif; ?>

		<?php if (@$_SERVER["SERVER_NAME"] != "localhost") : ?>
		<div id="disqus_thread"></div>
		<script>
			var disqus_shortname = 'mdref';
			var disqus_identifier = '<?=$ref?>';
			(function() {
				var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
				dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
				(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
			})();
		</script>
		<?php endif; ?>

		<footer>
			<?php include __DIR__."/footer.phtml" ?>
		</footer>
		<?php if (isset($baseUrl)) : ?>
			<script src="index.js"></script>
		<?php else : ?>
			<script type="application/javascript">
				<?= file_get_contents(__DIR__."/../public/index.js"); ?>
			</script>
		<?php endif; ?>
	</body>
</html>
