<?php ob_start() ?>

<?= $file($entry->getPath()) ?>

<?php if ($entry->isRoot() && $entry->getRepo()->hasStub($stub)) : ?>
	<h2 id="Editor.Stub:">Editor Stub:</h2>
	<p>This extension provides a stub file four your editor's auto-completion.</p>
	<?php include __DIR__ . "/stub.phtml"; ?>
<?php endif; ?>

<?php if ($entry->hasFunctions()) : ?>

<h2 id="Functions:">Functions:</h2>
<ul>
	<?php foreach($entry as $sub) : if (!$sub->isFunction()) continue; ?>

	<li>
		<h3><a href="<?= $esc($sub->getName()) ?>"><?= $esc($sub) ?></a></h3>
		<?= $quick($sub->getDescription()) ?>

		<p><?= $esc($sub->getTitle()) ?></p>
	</li>
	<?php endforeach; ?>

</ul>
<?php endif; ?>

<?php if ($entry->hasNsClasses()) : ?>

<h2 id="Namespaces,.Interfaces.and.Classes:">Namespaces, Interfaces and Classes:</h2>
<ul>
	<?php foreach ($entry as $sub) : if (!$sub->isNsClass()) continue; ?>

	<li>
		<h3><a href="<?= $esc($sub->getName()) ?>"><?= $esc($sub) ?></a></h3>
		<?= $quick($sub->getDescription()) ?>

		<p><?= $esc($sub->getTitle()) ?></p>
	</li>
	<?php endforeach; ?>

</ul>
<?php endif; ?>

<?= $markup(ob_get_clean()); ?>
