<?= $file($entry->getPath()) ?>

<?php if ($entry->hasFunctions()) : ?>
<h2>Functions:</h2>
<ul>
	<?php foreach($entry as $sub) : if (!$sub->isFunction()) continue; ?>
	<li>
		<h3><a href="<?= $view->esc($sub->getName()) ?>"><?= $view->esc($sub) ?></a></h3>
		<p><?= $quick($sub->getDescription()) ?></p>
		<p><?= $view->esc($sub->getTitle()) ?></p>
	</li>
	<?php endforeach; ?>
</ul>
<?php endif; ?>

<?php if ($entry->hasNsClasses()) : ?>
<h2>Namespaces, Interfaces and Classes:</h2>
<ul>
	<?php foreach ($entry as $sub) : if (!$sub->isNsClass()) continue; ?>
	<li>
		<h3><a href="<?= $view->esc($sub->getName()) ?>"><?= $view->esc($sub) ?></a></h3>
		<p><?= $quick($sub->getDescription()) ?></p>
		<p><?= $view->esc($sub->getTitle()) ?></p>
	</li>
	<?php endforeach; ?>
</ul>
<?php endif; ?>
