<div class="sidebar">
	<?php 
		if (isset($baseUrl) || !isset($entry)) {
			$up = "";
		} else {
			$up = str_repeat("../", count($entry->getParents()));
		}
	?>
	<ul>
		<li>&lsh; <a href="<?= $up ?>">Home</a>
			<?php if (isset($entry)) : /* @var \mdref\Entry $entry */ ?>
			<ul>
				<li>
					<?php foreach ($entry->getParents() as $parent) if ($parent->isFile()) : ?>
					&uarr; 
						<a href="<?= $up.$view->esc($parent->getName()) ?>">
							<?= $view->esc($entry->getRepo()->getEntry($parent)) ?>
						</a>
						<ul>
							<li>
					<?php endif; ?>
							&circlearrowright; <a href="<?= $up.$view->esc($entry->getName()) ?>"
							><?= $view->esc($entry) ?></a>
							<ul>
								<?php foreach ($entry as $sub) : /* @var \mdref\Entry $sub */ ?>
								<li>
									&rdsh; <a href="<?= $up.$view->esc($sub->getName()) ?>"
									><?= $view->esc($sub) ?></a>
								</li>
								<?php endforeach; ?>
							</ul>
					<?php foreach ($entry->getParents() as $parent) if ($parent->isFile()) : ?>
						</li>
					</ul>
					<?php endif; ?>
				</li>
			</ul>
			<?php elseif (isset($refs)) : ?>
			<ul>
				<?php foreach ($refs as $repo) : /* @var \mdref\Repo $repo */ ?>
					<?php foreach ($repo as $sub) : /* @var \mdref\Entry $entry */ ?>
						<li>
							&rdsh; <a href="<?= $view->esc($sub->getName()) ?>"
							><?= $view->esc($sub->getTitle()) ?></a>
						</li>
					<?php endforeach; ?>
				<?php endforeach; ?>
			</ul>
			<?php endif; ?>
		</li>
	</ul>
	<?php if (isset($entry)) : ?>
	<div class="edit">
		<a href="<?= $entry->getEditUrl() ?>">Edit</a>
	</div>
	<?php endif; ?>
</div>

